#!/bin/bash -l

#SBATCH --qos debug

##SBATCH --qos regular
##SBATCH --qos=premium

#SBATCH --account=atom

#SBATCH --nodes=1
#SBATCH -t 00:30:00
#SBATCH -C cpu

#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out

#SBATCH --image=registry.services.nersc.gov/parkjm/ips-fastran:latest
#SBATCH --volume="/global/cscratch1/sd/rwp/tmpfiles:/tmp:perNodeCache=size=10G"

WORK_DIRECTORY=test_massive_parallel_runner_3

rm -rf $SCRATCH/$WORK_DIRECTORY
mkdir $SCRATCH/$WORK_DIRECTORY
cp -rd * $SCRATCH/$WORK_DIRECTORY
cd $SCRATCH/$WORK_DIRECTORY

conda activate /global/common/software/atom/perlmutter/adaptive/conda

ips.py --platform=platform.conf --simulation=ips.massive_parallel_runner.config

wait
