#!/bin/bash -l

#SBATCH -p debug

##SBATCH -p regular
##SBATCH --qos=premium

#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH -t 00:30:00
#SBATCH -C haswell

#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out

#SBATCH -C haswell

#SBATCH --image=docker:registry.services.nersc.gov/rwp53/ips-massive-serial:latest
#SBATCH --volume="/global/cscratch1/sd/rwp/tmpfiles:/tmp:perNodeCache=size=1G"

conda activate fastran

export PYTHONPATH="$PYTHONPATH:$HOME/systemcode"

rm -rf $SCRATCH/test_massive_serial_runner_shifter
mkdir $SCRATCH/test_massive_serial_runner_shifter
cp -rd * $SCRATCH/test_massive_serial_runner_shifter
cd $SCRATCH/test_massive_serial_runner_shifter

ips.py --platform=platform.conf --simulation=ips.massive_serial_runner.config

wait
