#!/bin/bash -l

#SBATCH -p debug
##SBATCH -q early_science

#SBATCH --account=atom_g

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH -t 00:30:00

#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out

#SBATCH -C gpu
#SBATCH -c 128
#SBATCH --gpus-per-node=1

##SBATCH --image=docker:registry.services.nersc.gov/rwp53/ips-massive-serial:latest
##SBATCH --volume="/global/cscratch1/sd/rwp/tmpfiles:/tmp:perNodeCache=size=1G"

conda activate massive_vmec

ips.py --simulation=ips.massive_vmec_runner.config --platform=platform.conf

wait
