#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH -C haswell
#SBATCH --nodes=2
#SBATCH --time=00:30:00
#SBATCH --output=log.slurm.stdOut

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior

#clean current directory:
if [ -f cleanIpsRun.sh ]; then
   echo "clean up directory"
   ./cleanIpsRun.sh
else
   echo "WARNING: not cleaning up submission directory"
fi

conda activate solps-ftx

#for these tests, source them locally 
#  Comment these out for now.
#source $SLURM_SUBMIT_DIR/env.ips.cori #.python3
#source $SLURM_SUBMIT_DIR/env.GITR.cori.AL.sh

#add this to run the correct binTridyn file (located in submission directory)
#  Comment this out for now PYTHONPATH should be moved to the conda env.
#export PYTHONPATH=$SLURM_SUBMIT_DIR:$PYTHONPATH

module load PrgEnv-intel/6.0.5 intel/19.0.3.199
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/11.2.0/snos/lib64

#export OMP_NUM_THREADS=32
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

module list
ips.py --config=ips.parent.conf --platform=conf.ips.cori --log=log.framework 2>>log.stdErr 1>>log.stdOut

egrep -i 'error' log.* > log.errors
./setPermissions.sh


setfacl -R -m u:sblondel:r .
