PROGRAM generic_ps_init

! Fortran code for generic_ps_init.py.  the  Swiss army knife of Plasma State initializers.
! 
! This version combines several previous initializer routines and extends them.  There are
! X modes of initialization to be specified by the config file variable INIT_MODE
! 
! INIT_MODE = minimal
! This is exctly the same as the previous generic_ps_init.py. It produces a CURRENT_STATE 
! that is empty except for:
! time variables - ps%t0, ps%t1, ps%tinit, and ps%tfinal 
! simulation identifiers - ps%tokamak_id, ps%shot_number, ps%run_id.  
! ps%Global_label is set to run_id_tokamak_id_shot_number.
! 
! INIT_MODE = existing_ps_file
! This copies an existing input plasma state file
! 
! 
! INIT_MODE = mdescr
! This performs a minimal init as descrbed above then initializes all machine description 
! data from a plasma state machine description file <tokamak>.mdescr using the plasma 
! state function ps_mdescr_read().  

! INIT_MODE = mixed (yet to be implemented)

!--------------------------------------------------------------------------
!
! Simulation init component that produces a plasma state that is empty except for:
! time variables - t0, t1, tinit, and tfinal, 
! and
! simulation identifiers - tokamak_id, shot_number, run_id.  
! Also the plasma state variable Global_label is set to run_id_tokamak_id_shot_number.
!
!   Note: There is a potential problem with Global_label.  
!   Global_lable is dimensioned CHARACTER(*80) in the state, whereas the other identifiers
!   are CHARACTER(*32).  So if they were all maximal length, Global_label would turn out 
!   to be 3*32 + 2 = 98.  (The extra 2 are the joining underscores). I hope the value 
!   would just be truncated.
!
! This code is launched by the component script generic_ps_init.py
! 
! Data for this code comes in from generic_ps_init.nml, whereas the previous 
! minimal_state_init.f90 got input data from command line args
!
! N.B. Both ps%t0 and ps%t1 are set to the value time_stamp.  ps%tinit and ps%tfinal
!      are generated by the Python component from the TIME_LOOP variable in the
!      simulation config file.  Note that the initial ps%t0 can be different from 
!      ps%tinit, as might be needed in a restart.

!! N.B. The other plasma state files that were produced by the previous versions of
!      this fortran code are now produced in the generic_ps_init.py. These files
!      include prior_state file and next file as well as the dummy files: cur_cql_file
!      cur_eqdsk_file, cur_dql_file, and cur_jsdsk_file.
!
!       Don Batchelor
!       ORNL
!       Oak Ridge, TN 37831
!       batchelordb@ornl.gov
!
!--------------------------------------------------------------------------
  

    USE plasma_state_mod
    

    use swim_global_data_mod, only : &
            & rspec, ispec, &               ! int: kind specification for real and integer
            & SWIM_name, SWIM_filename, &   ! derived data types: containing one character
            								! string
            & SWIM_error                    ! subroutine: a simple error handling routine
    
    IMPLICIT none
    
    INTEGER :: istat, ierr = 0
    INTEGER :: iarg
    
	CHARACTER (len=256) :: cur_state_file
	CHARACTER*32 :: tokamak_id, shot_number, run_id
    CHARACTER(len=32) :: time_stamp, char_tinit, char_tfinal


!--------------------------------------------------------------------------
!
!   Internal data: None
!
!--------------------------------------------------------------------------

	REAL(KIND=rspec) :: t, tinit, tfinal
	PARAMETER, CHARACTER* :: input_nml_file = 'generic_ps_init.nml'

!------------------------------------------------------------------------------------
!     
!   Namelists
!
!------------------------------------------------------------------------------------

    namelist /genric_ps_init/ &
          cur_state_file, tokamak_id, shot_number, run_id, tinit, tfinal, time_stamp, &
          init_mode, mdescr_file, 

!---------------------------------------------------------------------------------
!     
!  Do minimal initialization
!  Get minimal plasma state data from input_nml_file
!
!---------------------------------------------------------------------------------

       OPEN (unit=21, file=TRIM(input_namelist_file), status='unknown', &
            action='write', iostat=istat, form='formatted')
            IF (istat /= 0 ) THEN
                CALL SWIM_error ('open', 'generic_ps_init.f90',input_nml_file)
                ierr = istat
                stop 'cannot open input_nml_file'
            END IF
        ierr = 0

        read(21, nml=static_state_data)
        CLOSE (21)
        WRITE (*, nml = static_state_data)
      
	WRITE (*,*)
	WRITE (*,*) 'generic_ps_init'      
      print*, 'cur_state_file = ', trim(cur_state_file)      
      print*, 'tokamak = ', trim(tokamak_id)
      print*, 'shot number = ', trim(shot_number)
      print*, 'run_id = ', trim(run_id)
      print*, 'tinit = ', trim(char_tinit)
      print*, 'tfinal = ', trim(char_tfinal)
      print*, 'time_stamp = ', trim(time_stamp)

	!------------------------------------------------------------------------------------
	!     
	!   Put run idnetifiers into plasma state obtained from USE plasma_state_mod
	!
	!------------------------------------------------------------------------------------

	ps%tokamak_id = trim( tokamak_id(1:32) )
	ps%RunID = trim( run_id(1:32) )
	
	read (shot_number, *) ps%shot_number
	
	ps%Global_label = trim(run_id)//'_'//trim(tokamak_id)//'_'//trim(shot_number)
 
	!-----------------------------------
	! Insert time at beginning and end of time step (both are time_stamp on initialization)
	!-----------------------------------
	READ (time_stamp, '(f12.6)') t
	WRITE (*,*) 'generic_ps_init INIT: time stamp t = ', t
	 
	ps%t0 = t
	ps%t1 = ps%t0

	READ (char_tinit, '(f12.6)') tinit
	READ (char_tfinal, '(f12.6)') tfinal
	WRITE (*,*) 'generic_ps_init INIT: tinit = ', tinit, '   tfinal = ', tfinal
	 
	ps%tinit = tinit
	ps%tfinal = tfinal


!------------------------------------------------------------------------------------
!     
!   Do initalizations from input plasma state file
!
!------------------------------------------------------------------------------------

	IF TRIM(init_mode) == 'existing_ps_file'
    	call ps_mdescr_read(trim(mdescr_file), ierr, state=ps)

!------------------------------------------------------------------------------------
!     
!   Do initalizations from machine description file
!
!------------------------------------------------------------------------------------

	IF TRIM(init_mode) == 'mdescr'
    	call ps_mdescr_read(trim(mdescr_file), ierr, state=ps)

!------------------------------------------------------------------------------------
!     
!   Store minimal initial plasma state
!
!------------------------------------------------------------------------------------

	CALL PS_STORE_PLASMA_STATE(ierr, cur_state_file)
	
	WRITE (*,*) "generic_ps_init.f90: Stored initial Plasma State"    

	ELSE
		WRITE (*,*) 'Unknown initialization moe = ', init_mode

END PROGRAM generic_ps_init

