name: Static Analysis

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python testing dependencies
      run: python -m pip install flake8==3.9.2
    - name: flake8
      run: flake8
